name: dart_service_announcement
description: Helper libraries for creating discoverable development services
version: 1.0.0
homepage: https://github.com/Chimerapps/dart_tooling_announcement

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.0
  synchronized: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.0