name: dart_service_announcement
description: Helper libraries for creating discoverable development services
version: 0.1.0
homepage: https://github.com/Chimerapps/dart_tooling_announcement

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  synchronized: ^2.1.0
  logging: ^0.11.4
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
